require('basic')
require('keybindings')

require('plugins')
require('hop').setup()
require('plugin_config/lualine')
require('plugin_config/nvim-tree')
require('plugin_config/nvim-treesitter')
require('plugin_config/vim-mundo')
require('plugin_config/rust-tools')
require('plugin_config/nvim-cmp')
