require('basic')
require('keybindings')

require('plugins')
require('plugin_config/flash')
require('plugin_config/telescope')
require('plugin_config/lualine')
require('plugin_config/treesitter')
require('plugin_config/blankline')
require('plugin_config/cmp')
require('plugin_config/lspconfig')
