require('basic')
require('keybindings')

require('plugins')
-- require('plugin_config/bufferline')
require('plugin_config/lualine')
require('plugin_config/indent-blankline')
require('plugin_config/nvim-treesitter')
require('plugin_config/nvim-telescope')
require('plugin_config/flash')
require('plugin_config/nvim-cmp')
require('plugin_config/nvim-lspconfig')
